# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

increQIF_ar1 <- function(X, y, x_save, y_save, nobs, family, beta_old, g_accum, S_accum, C_accum, maxit, tol) {
    .Call(`_SSLA_increQIF_ar1`, X, y, x_save, y_save, nobs, family, beta_old, g_accum, S_accum, C_accum, maxit, tol)
}

