# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_inv <- function(X) {
    .Call(`_SLA_matrix_inv`, X)
}

obj_eval_ar1 <- function(X, y, nobs, family, beta) {
    .Call(`_SLA_obj_eval_ar1`, X, y, nobs, family, beta)
}

increQIF_ar1 <- function(X, y, x_save, y_save, nobs, family, beta_old, beta_init, g_accum, g_all_accum, S_i_accum, S_accum, q, maxit, tol) {
    .Call(`_SLA_increQIF_ar1`, X, y, x_save, y_save, nobs, family, beta_old, beta_init, g_accum, g_all_accum, S_i_accum, S_accum, q, maxit, tol)
}

try_increQIF_ar1 <- function(X, y, x_save, y_save, nobs, family, beta_old, beta_init, g_accum, g_all_accum, S_i_accum, S_accum, q, maxit, tol) {
    .Call(`_SLA_try_increQIF_ar1`, X, y, x_save, y_save, nobs, family, beta_old, beta_init, g_accum, g_all_accum, S_i_accum, S_accum, q, maxit, tol)
}

online_weighted_score <- function(X, y, nobs, family, beta_old, beta_init, g_accum, g_all_accum, S_i_accum, S_accum, q, maxit, tol) {
    .Call(`_SLA_online_weighted_score`, X, y, nobs, family, beta_old, beta_init, g_accum, g_all_accum, S_i_accum, S_accum, q, maxit, tol)
}

